// PrintReport.js
import { faPrint } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import React, { useRef, useState, useEffect } from 'react';
import { useReactToPrint } from 'react-to-print';
import './styles.css';

const PrintReport = ({ children, title }) => {
  const [username, setUsername] = useState('');
  const [dateTime, setDateTime] = useState({
    date: '',
    time: '',
  });
  const printRef = useRef();

  useEffect(() => {
    // Fetch username from localStorage
    const storedUsername = localStorage.getItem('adminUName');
    setUsername(storedUsername || 'Unknown User');

    // Get current date and time
    const now = new Date();
    setDateTime({
      date: now.toLocaleDateString(),
      time: now.toLocaleTimeString(),
    });
  }, []);

  const handlePrint = useReactToPrint({
    content: () => printRef.current,
    pageStyle: `
      @media print {
        @page {
          size: auto;
          margin: 20mm;
        }
        table {
          page-break-inside: auto;
          width: 100%;
          border-collapse: collapse;
        }
        tr {
          page-break-inside: avoid;
          page-break-after: auto;
        }
        th, td {
          padding: 8px;
          border: 1px solid #000;
          word-wrap: break-word;
        }
      }
    `,
  });

  return (
    <div className='flex flex-col items-end'>
      <div className='bg-red-900 text-white pt-4 pb-4 flex justify-center 
      items-center rounded-full shadow-md w-16 mb-4 mr-4 cursor-pointer btn no-print'
      onClick={handlePrint}>
        <FontAwesomeIcon icon={faPrint} />
      </div>
      <div ref={printRef} className="print-container">
        <div className="print-header">
          <h1>{title} Report</h1>
        </div>
        <p>Date: {dateTime.date}</p>
        <p>Time: {dateTime.time}</p>
        <p>Generated by: {username}</p>
        <div className="print-content">
          {children}
        </div>
      </div>
    </div>
  );
};

export default PrintReport;
